version: '3'

services:
  app:
    build: .
    container_name: nodejs-api-testing-app
    ports:
      - 3001:3000
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    container_name: nodejs-api-testing-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: nodejs_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/scripts/create-tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/scripts/create-testdb.sql:/docker-entrypoint-initdb.d/2.sql
volumes:
  db-data:
